[SamplerDX11_1]
[SamplerDX11_2]

ComparisonFunc = D3D11_COMPARISON_GREATER_EQUAL
Filter = D3D11_FILTER_COMPARISON_MIN_MAG_LINEAR_MIP_POINT
AddressU       = D3D11_TEXTURE_ADDRESS_CLAMP
AddressV       = D3D11_TEXTURE_ADDRESS_CLAMP

[DepthStencilStateDX11]
DepthEnable = true
DepthFunc = D3D11_COMPARISON_GREATER_EQUAL
depthwritemask = D3D11_DEPTH_WRITE_MASK_ALL
